{{define "mapper"}}
package {{.MapperPackageName}}

/**
 * Generated by sqlxx.
 */

public interface {{.MapperClassName}} {
  // =========================================== QUERY START ===========================================

  {{.ModelClassName}} getById(@Param("id") Long id);

  // =========================================== QUERY START ===========================================

  // =========================================== UPDATE START ==========================================

  {{.ModelClassName}} update(@Param("{{.ModelParamName}}") {{.ModelClassName}} {{.ModelParamName}});

  // =========================================== UPDATE END ============================================

  // =========================================== INSERT START ==========================================

  Integer add(@Param("{{.ModelParamName}}") {{.ModelClassName}} {{.ModelParamName}});

  // =========================================== INSERT END ============================================

  // =========================================== DELETE START ==========================================

  Integer deleteById(@Param("id") Long id);

  // =========================================== DELETE END ============================================
}

{{end}}